#!/usr/bin/env bash
set -euo pipefail

FIND_BIN="find"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/.local"
CONFIG_FILE="$CONFIG_DIR/appstoreconnect-upload.env"
STABLE_ARCHIVE_SCRIPT="$REPO_ROOT/scripts/archive_lumen_stable.sh"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
info() { printf "\n➡️  %s\n" "$1"; }
warn() { printf "\n⚠️  %s\n" "$1"; }
fail() { printf "\n❌ %s\n" "$1"; exit 1; }

confirm() {
  local prompt="$1"
  local response
  read -r -p "$prompt [y/N]: " response
  [[ "$response" =~ ^[Yy]$ ]]
}

read_required() {
  local prompt="$1"
  local var=""
  while [[ -z "${var// }" ]]; do
    read -r -p "$prompt" var
  done
  printf "%s" "$var"
}

read_secret_required() {
  local prompt="$1"
  local var=""
  while [[ -z "${var// }" ]]; do
    read -r -s -p "$prompt" var
    printf "\n"
  done
  printf "%s" "$var"
}

read_with_default() {
  local prompt="$1"
  local default_value="$2"
  local value=""
  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " value
    printf "%s" "${value:-$default_value}"
  else
    read_required "$prompt: "
  fi
}

read_yes_no_with_default() {
  local prompt="$1"
  local default_value="$2"
  local response=""
  local label="y/N"
  [[ "$default_value" =~ ^[Yy]$ ]] && label="Y/n"
  read -r -p "$prompt [$label]: " response
  response="${response:-$default_value}"
  [[ "$response" =~ ^[Yy]$ ]]
}

load_local_config() {
  if [[ "${LUMEN_RESET_ASC_CONFIG:-0}" == "1" ]]; then
    rm -f "$CONFIG_FILE"
    warn "Local App Store Connect config reset: $CONFIG_FILE"
    return 0
  fi

  if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
  fi
}

save_local_config() {
  mkdir -p "$CONFIG_DIR"
  local tmp_file="$CONFIG_FILE.tmp"
  umask 077
  {
    printf '# Local Lumen App Store Connect upload config. Generated by scripts/build_and_submit_appstoreconnect.sh.\n'
    printf '# This file is intentionally ignored by Git. Do not commit API keys or private credentials.\n'
    printf 'ASC_PROJECT_PATH=%q\n' "$PROJECT_PATH"
    printf 'ASC_SCHEME=%q\n' "$SCHEME"
    printf 'ASC_CONFIGURATION=%q\n' "$CONFIGURATION"
    printf 'ASC_TEAM_ID=%q\n' "$TEAM_ID"
    printf 'ASC_EXPORT_METHOD=%q\n' "$EXPORT_METHOD"
    printf 'ASC_AUTH_MODE=%q\n' "$AUTH_MODE"
    printf 'ASC_API_KEY=%q\n' "$API_KEY"
    printf 'ASC_API_ISSUER=%q\n' "$API_ISSUER"
    printf 'ASC_API_KEY_DIR=%q\n' "$API_KEY_DIR"
    printf 'ASC_APPLE_ID=%q\n' "$APPLE_ID"
    printf 'ASC_PROVIDER=%q\n' "$ASC_PROVIDER"
    printf 'ASC_UPLOAD_AFTER_BUILD=%q\n' "${UPLOAD_AFTER_BUILD:-}"
  } > "$tmp_file"
  mv "$tmp_file" "$CONFIG_FILE"
  chmod 600 "$CONFIG_FILE"
}

install_xcode_cli_tools() {
  if xcode-select -p >/dev/null 2>&1; then
    return 0
  fi

  info "Xcode Command Line Tools are not installed."
  if ! confirm "Install Xcode Command Line Tools now via xcode-select --install?"; then
    fail "Xcode Command Line Tools are required."
  fi

  xcode-select --install || true
  warn "Complete the GUI installer, then re-run this script."
  exit 1
}

ensure_find() {
  if command -v find >/dev/null 2>&1; then
    FIND_BIN="$(command -v find)"
    export FIND_BIN
    return 0
  fi

  warn "find command is missing. Attempting to install GNU findutils via Homebrew."
  if ! command -v brew >/dev/null 2>&1; then
    fail "Homebrew is not installed; install Homebrew or restore /usr/bin/find."
  fi

  brew install findutils
  if command -v find >/dev/null 2>&1; then
    FIND_BIN="$(command -v find)"
    export FIND_BIN
    return 0
  fi
  if [[ -x /opt/homebrew/opt/findutils/libexec/gnubin/find ]]; then
    FIND_BIN="/opt/homebrew/opt/findutils/libexec/gnubin/find"
  elif [[ -x /usr/local/opt/findutils/libexec/gnubin/find ]]; then
    FIND_BIN="/usr/local/opt/findutils/libexec/gnubin/find"
  else
    fail "find installation did not expose expected binary under /opt/homebrew or /usr/local gnubin paths."
  fi
  export FIND_BIN
}

ensure_xcodebuild_and_xcrun() {
  install_xcode_cli_tools

  if ! command -v xcodebuild >/dev/null 2>&1 || ! command -v xcrun >/dev/null 2>&1; then
    fail "xcodebuild/xcrun unavailable. Install Xcode and select it with: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer"
  fi

  xcodebuild -version >/dev/null 2>&1 || fail "xcodebuild is installed but not usable. Open Xcode once and accept licenses."
}

ensure_upload_tool() {
  if ! xcrun altool --help >/dev/null 2>&1; then
    fail "xcrun altool is unavailable. Install/upgrade Xcode and select it with: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer"
  fi
}

print_xcode_log_diagnostics() {
  local log_path="$1"
  [[ -f "$log_path" ]] || return 0

  warn "xcodebuild failed. Full log: $log_path"

  info "Most relevant diagnostics from xcodebuild log"
  grep -nEi \
    '(^|[^A-Za-z])(error:|fatal error:|warning:|failed|failure|Command SwiftCompile failed|Command CompileSwift failed|Command CodeSign failed|no such module|cannot find|cannot convert|ambiguous|missing|undefined|duplicate|provisioning|codesign|SwiftDriver|CompileSwift)' \
    "$log_path" | tail -n 120 || true

  info "Last 220 lines of xcodebuild log"
  tail -n 220 "$log_path" || true
}

run_logged() {
  local log_path="$1"
  shift
  mkdir -p "$(dirname "$log_path")"

  set +e
  "$@" 2>&1 | tee "$log_path"
  local status=${PIPESTATUS[0]}
  set -e

  if [[ $status -ne 0 ]]; then
    print_xcode_log_diagnostics "$log_path"
    return "$status"
  fi

  return 0
}

normalize_export_method() {
  case "$1" in
    app-store|app-store-connect) printf "app-store-connect" ;;
    ad-hoc|release-testing) printf "release-testing" ;;
    development|debugging) printf "debugging" ;;
    enterprise) printf "enterprise" ;;
    validation) printf "validation" ;;
    *) return 1 ;;
  esac
}

is_distribution_export() {
  case "$1" in
    app-store-connect|release-testing|enterprise|validation) return 0 ;;
    *) return 1 ;;
  esac
}

write_export_options_plist() {
  local plist_path="$1"
  local export_method="$2"
  local team_id="$3"
  local signing_certificate="$4"

  cat > "$plist_path" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>${export_method}</string>
  <key>signingStyle</key>
  <string>automatic</string>
  <key>signingCertificate</key>
  <string>${signing_certificate}</string>
PLIST

  if [[ -n "$team_id" ]]; then
    cat >> "$plist_path" <<PLIST
  <key>teamID</key>
  <string>${team_id}</string>
PLIST
  fi

  cat >> "$plist_path" <<PLIST
  <key>stripSwiftSymbols</key>
  <true/>
  <key>uploadSymbols</key>
  <true/>
</dict>
</plist>
PLIST
}

[[ "$(uname -s)" == "Darwin" ]] || fail "This script must run on macOS."
cd "$REPO_ROOT"
load_local_config
ensure_xcodebuild_and_xcrun
ensure_find

bold "Lumen iOS build + App Store Connect upload"

DEFAULT_PROJECT_PATH="${ASC_PROJECT_PATH:-ios/Lumen.xcodeproj}"
DEFAULT_SCHEME="${ASC_SCHEME:-Lumen}"
DEFAULT_CONFIGURATION="${ASC_CONFIGURATION:-Release}"
DEFAULT_EXPORT_METHOD="${ASC_EXPORT_METHOD:-app-store-connect}"
DEFAULT_TEAM_ID="${ASC_TEAM_ID:-${DEVELOPMENT_TEAM:-52T7P32J34}}"
DEFAULT_AUTH_MODE="${ASC_AUTH_MODE:-1}"

PROJECT_PATH="$(read_with_default 'Project/workspace path' "$DEFAULT_PROJECT_PATH")"
[[ -e "$PROJECT_PATH" ]] || fail "Path not found: $PROJECT_PATH"
[[ "$PROJECT_PATH" == *.xcworkspace || "$PROJECT_PATH" == *.xcodeproj ]] || fail "Path must be .xcworkspace or .xcodeproj"
[[ -f "$STABLE_ARCHIVE_SCRIPT" ]] || fail "Stable archive script not found: $STABLE_ARCHIVE_SCRIPT"

SCHEME="$(read_with_default 'Scheme' "$DEFAULT_SCHEME")"
CONFIGURATION="$(read_with_default 'Configuration' "$DEFAULT_CONFIGURATION")"
TEAM_ID="$(read_with_default 'Apple Developer Team ID' "$DEFAULT_TEAM_ID")"

EXPORT_METHOD_INPUT="$(read_with_default 'Export method' "$DEFAULT_EXPORT_METHOD")"
EXPORT_METHOD="$(normalize_export_method "$EXPORT_METHOD_INPUT")" || fail "Unsupported export method: $EXPORT_METHOD_INPUT"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
SCHEME_SAFE="${SCHEME//[^A-Za-z0-9_.-]/_}"
ARCHIVE_PATH="build/${SCHEME_SAFE}-${TIMESTAMP}.xcarchive"
EXPORT_DIR="build/export-${SCHEME_SAFE}-${TIMESTAMP}"
EXPORT_OPTIONS_PLIST="build/export-options-${SCHEME_SAFE}-${TIMESTAMP}.plist"
LOG_DIR="build/logs"
EXPORT_LOG="$LOG_DIR/export-${SCHEME_SAFE}-${TIMESTAMP}.log"

mkdir -p build "$LOG_DIR"

bold "Choose auth mode"
echo "1) App Store Connect API key (recommended)"
echo "2) Apple ID + app-specific password"
AUTH_MODE="$(read_with_default 'Select [1/2]' "$DEFAULT_AUTH_MODE")"

API_KEY=""
API_ISSUER=""
API_KEY_DIR=""
API_KEY_PATH=""
APPLE_ID=""
APP_SPECIFIC_PASSWORD=""
ASC_PROVIDER="${ASC_PROVIDER:-}"
UPLOAD_AFTER_BUILD="${ASC_UPLOAD_AFTER_BUILD:-}"

case "$AUTH_MODE" in
  1)
    API_KEY="$(read_with_default 'API key ID' "${ASC_API_KEY:-}")"
    API_ISSUER="$(read_with_default 'API issuer ID (UUID)' "${ASC_API_ISSUER:-}")"
    API_KEY_DIR="$(read_with_default 'Directory containing AuthKey_<KEYID>.p8' "${ASC_API_KEY_DIR:-}")"
    [[ -d "$API_KEY_DIR" ]] || fail "API key directory not found: $API_KEY_DIR"
    API_KEY_PATH="$API_KEY_DIR/AuthKey_${API_KEY}.p8"
    [[ -f "$API_KEY_PATH" ]] || fail "Missing API key file: $API_KEY_PATH"
    ASC_PROVIDER="$(read_with_default 'Optional provider short name, or blank to skip' "$ASC_PROVIDER")"
    ;;
  2)
    APPLE_ID="$(read_with_default 'Apple ID (email)' "${ASC_APPLE_ID:-}")"
    APP_SPECIFIC_PASSWORD="$(read_secret_required 'App-specific password: ')"
    ASC_PROVIDER="$(read_with_default 'Optional provider short name, or blank to skip' "$ASC_PROVIDER")"
    warn "Apple ID auth can upload the IPA, but automatic profile creation still depends on Xcode being signed into your Apple Developer account."
    ;;
  *)
    fail "Invalid auth mode."
    ;;
esac

save_local_config
info "Saved local defaults to $CONFIG_FILE"

SIGNING_CERTIFICATE="Apple Development"
if is_distribution_export "$EXPORT_METHOD"; then
  SIGNING_CERTIFICATE="Apple Distribution"
fi

write_export_options_plist "$EXPORT_OPTIONS_PLIST" "$EXPORT_METHOD" "$TEAM_ID" "$SIGNING_CERTIFICATE"

XCODE_AUTH_ARGS=()
if [[ "$AUTH_MODE" == "1" ]]; then
  XCODE_AUTH_ARGS+=(
    -authenticationKeyPath "$API_KEY_PATH"
    -authenticationKeyID "$API_KEY"
    -authenticationKeyIssuerID "$API_ISSUER"
  )
fi

info "Archive via stable linker-safe archive script"
ARCHIVE_ENV=(
  "LUMEN_ARCHIVE_PATH=$REPO_ROOT/$ARCHIVE_PATH"
  "LUMEN_IOS_PROJECT_PATH=$PROJECT_PATH"
  "LUMEN_IOS_SCHEME=$SCHEME"
  "LUMEN_IOS_CONFIGURATION=$CONFIGURATION"
  "LUMEN_IOS_ALLOW_PROVISIONING_UPDATES=1"
  "LUMEN_IOS_CODE_SIGN_STYLE=Automatic"
  "LUMEN_IOS_DEVELOPMENT_TEAM=$TEAM_ID"
  "LUMEN_IOS_CLEAR_PROVISIONING_PROFILE_SPECIFIER=1"
)
if [[ "$AUTH_MODE" == "1" ]]; then
  ARCHIVE_ENV+=(
    "LUMEN_IOS_AUTHENTICATION_KEY_PATH=$API_KEY_PATH"
    "LUMEN_IOS_AUTHENTICATION_KEY_ID=$API_KEY"
    "LUMEN_IOS_AUTHENTICATION_KEY_ISSUER_ID=$API_ISSUER"
  )
fi

env "${ARCHIVE_ENV[@]}" bash "$STABLE_ARCHIVE_SCRIPT"

info "Export IPA"
run_logged "$EXPORT_LOG" \
  xcodebuild \
    -exportArchive \
    -archivePath "$ARCHIVE_PATH" \
    -exportPath "$EXPORT_DIR" \
    -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
    -allowProvisioningUpdates \
    "${XCODE_AUTH_ARGS[@]}"

IPA_PATH="$("$FIND_BIN" "$EXPORT_DIR" -maxdepth 1 -type f -name '*.ipa' -print -quit)"
[[ -n "$IPA_PATH" ]] || fail "No IPA found in $EXPORT_DIR"

bold "Built IPA: $IPA_PATH"
if [[ -z "$UPLOAD_AFTER_BUILD" ]]; then
  if read_yes_no_with_default "Upload this IPA to App Store Connect now?" "Y"; then
    UPLOAD_AFTER_BUILD="Y"
  else
    UPLOAD_AFTER_BUILD="N"
  fi
  save_local_config
fi

if [[ ! "$UPLOAD_AFTER_BUILD" =~ ^[Yy]$ ]]; then
  warn "Upload skipped. IPA is ready at: $IPA_PATH"
  exit 0
fi

ensure_upload_tool
info "Upload via altool"
UPLOAD_CMD=(xcrun altool --upload-app --type ios --file "$IPA_PATH")
[[ -n "$ASC_PROVIDER" ]] && UPLOAD_CMD+=(--asc-provider "$ASC_PROVIDER")
if [[ "$AUTH_MODE" == "1" ]]; then
  export API_PRIVATE_KEYS_DIR="$API_KEY_DIR"
  UPLOAD_CMD+=(--apiKey "$API_KEY" --apiIssuer "$API_ISSUER")
else
  export APP_SPECIFIC_PASSWORD
  UPLOAD_CMD+=(--username "$APPLE_ID" --password @env:APP_SPECIFIC_PASSWORD)
fi

if ! "${UPLOAD_CMD[@]}"; then
  unset APP_SPECIFIC_PASSWORD || true
  fail "Upload failed. Fix the App Store Connect validation errors above, then rerun the upload."
fi
unset APP_SPECIFIC_PASSWORD || true
bold "✅ Upload complete. Check App Store Connect for processing status."
