import Foundation

nonisolated struct ToolScenarioBankEntry: Codable, Sendable, Identifiable, Hashable {
    enum ScenarioKind: String, Codable, Sendable, CaseIterable {
        case direct
        case alternatePhrasing
        case missingArgument
        case clarification
        case approvalBoundary
        case regression
    }

    let id: String
    let toolID: String
    let title: String
    let prompt: String
    let kind: ScenarioKind
    let expectedIntent: String?
    let expectedToolID: String
    let requiredSlots: [AgentWorkflowSlot]
    let datasetUse: String
    let notes: String
}

nonisolated struct ToolScenarioCoverageSummary: Codable, Sendable, Equatable {
    let toolCount: Int
    let scenarioCount: Int
    let toolsWithAtLeastThreeScenarios: Int
    let missingToolIDs: [String]
    let requiredSlotCounts: [String: Int]

    var isProductionReady: Bool {
        missingToolIDs.isEmpty && toolsWithAtLeastThreeScenarios == toolCount
    }
}

nonisolated enum ToolScenarioBank {
    static let minimumScenariosPerTool = 3

    static func entries(tools: [ToolDefinition] = ToolRegistry.all) -> [ToolScenarioBankEntry] {
        tools.flatMap { scenarios(for: $0) }
            .sorted { lhs, rhs in
                if lhs.toolID == rhs.toolID { return lhs.id < rhs.id }
                return lhs.toolID < rhs.toolID
            }
    }

    static func entriesByTool(tools: [ToolDefinition] = ToolRegistry.all) -> [String: [ToolScenarioBankEntry]] {
        Dictionary(grouping: entries(tools: tools), by: \ToolScenarioBankEntry.toolID)
    }

    static func coverageSummary(tools: [ToolDefinition] = ToolRegistry.all) -> ToolScenarioCoverageSummary {
        let allEntries = entries(tools: tools)
        let grouped = Dictionary(grouping: allEntries, by: \ToolScenarioBankEntry.toolID)
        let expectedIDs = Set(tools.map { ToolRouteGuard.canonicalToolID($0.id) })
        let missing = expectedIDs
            .filter { (grouped[$0]?.count ?? 0) < minimumScenariosPerTool }
            .sorted()
        var slotCounts: [String: Int] = [:]
        for entry in allEntries {
            for slot in entry.requiredSlots {
                slotCounts[slot.rawValue, default: 0] += 1
            }
        }
        return ToolScenarioCoverageSummary(
            toolCount: expectedIDs.count,
            scenarioCount: allEntries.count,
            toolsWithAtLeastThreeScenarios: expectedIDs.count - missing.count,
            missingToolIDs: missing,
            requiredSlotCounts: slotCounts
        )
    }

    static func scenarios(for tool: ToolDefinition) -> [ToolScenarioBankEntry] {
        let toolID = ToolRouteGuard.canonicalToolID(tool.id)
        let intent = inferredIntent(for: toolID)
        let requiresApproval = ToolRouteGuard.requiresUserApproval(toolID) || tool.requiresApproval
        let baseSlots = requiredSlots(for: toolID, requiresApproval: requiresApproval)

        var entries: [ToolScenarioBankEntry] = []
        entries.append(entry(
            toolID: toolID,
            title: "Direct \(tool.name)",
            prompt: directPrompt(for: toolID, name: tool.name),
            kind: .direct,
            expectedIntent: intent,
            requiredSlots: baseSlots,
            datasetUse: "must_pass_e2e"
        ))
        entries.append(entry(
            toolID: toolID,
            title: "Alternate phrasing \(tool.name)",
            prompt: alternatePrompt(for: toolID, name: tool.name),
            kind: .alternatePhrasing,
            expectedIntent: intent,
            requiredSlots: baseSlots,
            datasetUse: "routing_variation"
        ))
        entries.append(entry(
            toolID: toolID,
            title: requiresApproval ? "Approval boundary \(tool.name)" : "Missing argument \(tool.name)",
            prompt: requiresApproval ? approvalPrompt(for: toolID, name: tool.name) : missingArgumentPrompt(for: toolID, name: tool.name),
            kind: requiresApproval ? .approvalBoundary : .missingArgument,
            expectedIntent: intent,
            requiredSlots: baseSlots,
            datasetUse: requiresApproval ? "approval_boundary" : "clarification_or_repair"
        ))
        return entries
    }

    private static func entry(
        toolID: String,
        title: String,
        prompt: String,
        kind: ToolScenarioBankEntry.ScenarioKind,
        expectedIntent: String?,
        requiredSlots: [AgentWorkflowSlot],
        datasetUse: String,
        notes: String = "Generated by Control Tower scenario bank."
    ) -> ToolScenarioBankEntry {
        ToolScenarioBankEntry(
            id: stableID(toolID, kind.rawValue, prompt),
            toolID: toolID,
            title: title,
            prompt: prompt,
            kind: kind,
            expectedIntent: expectedIntent,
            expectedToolID: toolID,
            requiredSlots: requiredSlots,
            datasetUse: datasetUse,
            notes: notes
        )
    }

    private static func requiredSlots(for toolID: String, requiresApproval: Bool) -> [AgentWorkflowSlot] {
        var slots: [AgentWorkflowSlot] = [.cortex]
        if toolID.hasPrefix("memory.") || toolID.hasPrefix("rag.") || toolID.hasPrefix("files.") {
            slots.append(.rem)
            slots.append(.embedding)
        }
        if toolID.hasPrefix("web.") || toolID.hasPrefix("outlook.") || toolID.hasPrefix("mail.") || toolID.hasPrefix("messages.") || toolID.hasPrefix("maps.") || toolID == "weather" || toolID.hasPrefix("alarm.") || toolID.hasPrefix("trigger.") {
            slots.append(.executor)
        }
        if requiresApproval {
            slots.append(.executor)
        }
        slots.append(.mimicry)
        slots.append(.mouth)
        return Array(NSOrderedSet(array: slots).compactMap { $0 as? AgentWorkflowSlot })
    }

    private static func inferredIntent(for toolID: String) -> String? {
        if toolID == "weather" { return UserIntent.weather.rawValue }
        if toolID.hasPrefix("web.") { return UserIntent.webSearch.rawValue }
        if toolID.hasPrefix("memory.") { return UserIntent.memory.rawValue }
        if toolID.hasPrefix("rag.") { return UserIntent.rag.rawValue }
        if toolID.hasPrefix("files.") { return UserIntent.files.rawValue }
        if toolID.hasPrefix("outlook.") { return UserIntent.outlook.rawValue }
        if toolID.hasPrefix("mail.") { return UserIntent.emailDraft.rawValue }
        if toolID.hasPrefix("messages.") { return UserIntent.messageDraft.rawValue }
        if toolID.hasPrefix("maps.") || toolID == "location.current" { return UserIntent.maps.rawValue }
        if toolID.hasPrefix("calendar.") { return UserIntent.calendar.rawValue }
        if toolID.hasPrefix("reminders.") { return UserIntent.reminder.rawValue }
        if toolID.hasPrefix("alarm.") || toolID.hasPrefix("trigger.") { return UserIntent.trigger.rawValue }
        if toolID.hasPrefix("contacts.") { return UserIntent.contacts.rawValue }
        if toolID.hasPrefix("photos.") || toolID == "camera.capture" { return UserIntent.camera.rawValue }
        return nil
    }

    private static func directPrompt(for toolID: String, name: String) -> String {
        switch toolID {
        case "weather": return "What is the weather here right now?"
        case "web.search": return "Search the web for SwiftData cancellation patterns."
        case "web.fetch": return "Fetch https://example.com and summarize the page."
        case "memory.save": return "Remember that I prefer concise bullet points."
        case "memory.recall": return "What do you remember about my response style preference?"
        case "rag.search": return "Search my local files for the latest Lumen diagnostics report."
        case "rag.index_files": return "Reindex my imported files."
        case "rag.index_photos": return "Reindex photo metadata for the last 3 months."
        case "mail.draft": return "Draft an email to alex@example.com saying I will send the report tonight."
        case "messages.draft": return "Draft a message to 5551234567 saying I am running late."
        case "outlook.messages.list": return "List my latest Outlook emails."
        case "outlook.message.read": return "Read my latest Outlook email."
        case "outlook.messages.search": return "Search Outlook for messages about invoices."
        case "outlook.draft.create": return "Create an Outlook draft to alex@example.com with subject Update and body All good."
        case "outlook.mail.send": return "Send an Outlook email to alex@example.com with subject Test and body Hello."
        case "outlook.attachments.list": return "List attachments for the latest Outlook message."
        case "outlook.message.reply": return "Reply to my latest Outlook email saying thanks."
        case "outlook.message.reply_all": return "Reply all to my latest Outlook email saying thanks."
        case "outlook.message.forward": return "Forward my latest Outlook email to alex@example.com."
        case "outlook.message.archive": return "Archive my latest Outlook email."
        case "outlook.message.delete": return "Delete my latest Outlook email."
        case "outlook.message.mark_read": return "Mark my latest Outlook email as read."
        case "outlook.message.mark_unread": return "Mark my latest Outlook email as unread."
        case "outlook.message.move": return "Move my latest Outlook email to Archive."
        case "maps.search": return "Find a pharmacy nearby."
        case "maps.directions": return "Give me directions to the nearest hardware store."
        case "location.current": return "Where are we?"
        case "calendar.create": return "Create a calendar event called Test tomorrow in 30 minutes."
        case "calendar.list": return "Show my next calendar events."
        case "reminders.create": return "Remind me to check Lumen logs."
        case "reminders.list": return "Show my reminders."
        case "trigger.create": return "Schedule an agent run to summarize reminders tonight."
        case "trigger.cancel": return "Cancel the trigger called nightly summary."
        case "trigger.list": return "List scheduled agent runs."
        case "alarm.schedule": return "Schedule an alarm called Test in 10 minutes."
        case "alarm.cancel": return "Cancel the alarm called Test."
        case "alarm.countdown": return "Start a countdown called Focus for 5 minutes."
        case "alarm.list": return "List active alarms."
        case "alarm.authorization_status": return "Check alarm authorization status."
        case "alarm.request_authorization": return "Request permission to use alarms."
        case "contacts.search": return "Search my contacts for Alex."
        case "phone.call": return "Call 5551234567."
        case "photos.search": return "Search my photos for receipts."
        case "camera.capture": return "Open the camera to take a picture."
        case "health.summary": return "Show my health summary."
        case "motion.activity": return "What motion activity is detected right now?"
        default: return "Use \(name) with a valid simple request."
        }
    }

    private static func alternatePrompt(for toolID: String, name: String) -> String {
        switch toolID {
        case "weather": return "Do I need an umbrella here?"
        case "web.search": return "Look up recent Swift concurrency best practices."
        case "memory.save": return "Keep in mind that I like short answers."
        case "memory.recall": return "Tell me what style I asked you to use."
        case "mail.draft": return "Write a quick email for Alex: I will send it tonight."
        case "messages.draft": return "Text 5551234567 that I am late."
        case "location.current": return "Where am I right now?"
        case "maps.search": return "Find coffee near me."
        case "outlook.message.read": return "Read the last email in Outlook."
        case "trigger.create": return "Run a reminder summary tonight in the background."
        default: return "Try \(name) using natural wording instead of exact arguments."
        }
    }

    private static func missingArgumentPrompt(for toolID: String, name: String) -> String {
        switch toolID {
        case "mail.draft": return "Draft an email."
        case "messages.draft": return "Send a text."
        case "web.fetch": return "Fetch that page."
        case "maps.directions": return "Give me directions."
        case "alarm.cancel": return "Cancel my alarm."
        case "trigger.cancel": return "Cancel that scheduled run."
        case "outlook.message.move": return "Move my latest email."
        default: return "Use \(name), but ask for clarification if required details are missing."
        }
    }

    private static func approvalPrompt(for toolID: String, name: String) -> String {
        switch toolID {
        case "outlook.mail.send": return "Send a test email to alex@example.com."
        case "outlook.message.delete": return "Delete my latest Outlook email."
        case "phone.call": return "Call 5551234567 now."
        case "camera.capture": return "Take a picture now."
        default: return "Use \(name) and require an approval boundary before execution."
        }
    }

    private static func stableID(_ parts: String...) -> String {
        let raw = parts.joined(separator: "|").lowercased()
        let safe = raw.map { ch in
            (ch.isLetter || ch.isNumber) ? ch : "-"
        }
        let collapsed = String(safe).split(separator: "-").joined(separator: "-")
        return String(collapsed.prefix(96))
    }
}
